on: [workflow_dispatch]

name: asana action
env:
  ASANA_PAT: ${{secrets.ASANA_PAT}}

jobs:
  build:
    name: asana action
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run node script
        uses: node --version

