on: [workflow_dispatch]

name: asana action

jobs:
  build:
    name: asana action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run node action
        env:
          ASANA_PAT: ${{secrets.ASANA_PAT}}
        uses: ./.github/actions/asana_task_list

