on: [workflow_dispatch]

name: asana action
env:
  ASANA_PAT: ${{secrets.ASANA_PAT}}

jobs:
  build:
    name: asana action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run node script
        run: node --version

      - name: npm install
        run: npm install asana

      - name: run asana query
        run: node .github/scripts/asana_query.js