on: [workflow_dispatch]

name: asana action
env:
  ASANA_PAT: ${{secrets.ASANA_PAT}}

jobs:
  build:
    name: asana action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: node version
        run: node --version

      - name: npm install
        run: npm install asana

      - name: run asana query
        id: asana_query
        run: |
          body=$(node .github/scripts/asana_query.js)
          echo $body
          echo "::set-output name=std_out::$body"

      - name: view set-output
        run: echo "${{ steps.asana_query.outputs.std_out }}"