on: [workflow_dispatch]

name: Create Main Merge PR

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release PR
        id: create-pull-request-for-main
        uses: actions/github-script@v3
        env:
          PRODUCTION_BRANCH: main
          TZ: Asia/Tokyo
        with:
          token: ${{ secrets.GIT_TOKEN }}
          script: |
            now = new Date()
            title_template = 'create-PR-from-action'
            title = title_template.concat(now.toString)
            github.pulls.create({
              owner: "Yasushi-Kanaya",
              repo: "git-test-kanaya",
              head: "staging",
              base: "main",
              title: "create-PR-from-action"
            });

