on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Rlease
        id: list-pull-request-for-main
        uses: actions/github-script@v3
        env:
          TZ: Asia/Tokyo
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            const pr_list = await github.pulls.list({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              state: "closed",
              base: "main"
            })
            console.log(pr_list.data[0])

            const tag_name = pr_list.data[0].title.replace(/[\/\-:_リリース]/g,'')
            const release_name = pr_list.data[0].title
            const release_body = pr_list.data[0].body

            const create_release = await github.createRelease({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              tag_name: tag_name,
              name: release_name,
              body: release_body
            });
            console.log(create_release)
ad
      - name: Slack Notification
        if: github.event.pull_request.merged == true
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: custom
          custom_payload: |
            {
              username: "Github Actions",
              icon_emoji: ":github:",
              channel: "${{ secrets.SLACK_CHANNEL_ID }}",
              attachments: [{
                color: '#00CB00',
                title: 'リリースお疲れさまでした:blobgo:',
                text: "リリースノートはこちら\n${{ steps.list-pull-request.outputs.list_url }}"
              }]
            }
