on: [workflow_dispatch]

name: Create Main Merge PR

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Git config
        run: |
          git config --global user.email "y.kanaya@bizreach.co.jp"
          git config --global user.name "GitHub Actions"

      - name: Create release PR
        id: create-pull-request-for-main
        uses: actions/github-script@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
        script: |
          github.pulls.create({
            owner: "Yasushi-Kanaya",
            repo: "git-test-kanaya",
            head: "staging",
            base: "main"
          });

