on:
  workflow_dispatch:
    branches:
      - staging

name: Create PR Staging to Main

jobs:
  build:
    name: Create PR staging to main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR
        id: create-pull-request-for-main
        uses: actions/github-script@v3
        env:
          TZ: Asia/Tokyo
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            now = new Date()
            date_str = ""
            hour = now.getHours()
            hour_str = hour.toString()
            if (hour < 10) {
              hour_str = hour_str.concat('0')
            }
            date_str = date_str.concat(now.getFullYear(),now.getMonth()+1,now.getDate(),hour_str,now.getMinutes())
            title_template = '-staging_to_main'
            title = date_str.concat(title_template)
            const pr_create = github.pulls.create({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              head: "staging",
              base: "main",
              title: title
            });

      - name: Slack Notification
        if: ${{ always() }}
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,eventName,ref
          username: "staging -> main マージPR"
          icon_emoji: ":github:"
          channel: ${{ secrets.SLACK_CHANNEL_ID }}

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: custom
          custom_payload: |
            {
              username: "Github Actions",
              icon_emoji: ":github:",
              channel: "${{ secrets.SLACK_CHANNEL_ID }}",
              attachments: [{
                color: '#9400d3',
                title: '[本番]デプロイ方式が選択できるよ！',
                title_link: 'https://jenkins.bizreach.jp/view/v1/job/deployment-config-update/',
                text: '*アニマルフレンドを選べるよ！*\n・一括(AllAtOnce)->全て一発で切替:winky:\n・カナリア(Canary)->5分間10%の後に切替:squawks:\n・リニア(Linear)->1分毎に10%ずつ切替:rambi:'
              }]
            }
