on:
  pull_request:
    types: [opened]
    branches:
      - main

name: Notify prd ready

jobs:
  build:
    name: Notify prd ready
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: custom
          custom_payload: |
            {
              username: "Github Actions",
              icon_emoji: ":github:",
              channel: "${{ secrets.SLACK_CHANNEL_ID }}",
              attachments: [{
                color: '#9400d3',
                title: '[本番]デプロイ方式が選択できるよ！',
                title_link: 'https://jenkins.bizreach.jp/view/v1/job/deployment-config-update/',
                text: '*アニマルフレンドを選べるよ！*\n・一括(AllAtOnce)->全て一発で切替:winky:\n・カナリア(Canary)->5分間10%の後に切替:squawks:\n・リニア(Linear)->1分毎に10%ずつ切替:rambi:'
              }]
            }

