on:
  push:
    branches:
      - master

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-env name=relase_date::$(git log --date=format:'%Y%m%d%H%M%S' --oneline --pretty=format:'%cd' -1)"
          echo """::set-env name=pr_number::`curl -s -H \"Authorization: token $GITHUB_TOKEN\" https://api.github.com/repos/Yasushi-Kanaya/git-test-kanaya/pulls?state=closed |jq '.[] | select( .title |test(\"^Release 20[0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9].*\")) | .number' |head -1`"""

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.release_date }}_${{ env.pr_number }}
          release_name: Release ${{ env.release_date }}_${{ env.pr_number }}
          body: ""
          draft: false
          prerelease: false
