on:
  push:
    # Sequence of patterns matched against refs/tags
    branch:
      - master # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Create Tag
        run: |
          export RELEASE_DATE=$(git log --date=format:'%Y%m%d%H%M%S' --oneline --pretty=format:'%cd' -1)
          export PR_NUMBER=$(git log --date=format:'%Y%m%d%H%M%S' --oneline --pretty=format:'%cd' -1)

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ""
          draft: false
          prerelease: false
